# Site settings
title: FreezeSoul's Code Matrix
meta_description: Exploring the code matrix - AI, Agents, RAG, and beyond
baseurl:  "" # Subpath, e.g. /blog/
url: "http://www.diginfo.me" # Base protocol and hostname
paginate: 1 # How many posts to show per page


# Google Analytics
google_analytics: UA-2291876-10

# Author settings
author_name: FreezeSoul
author_description: Full Stack Developer
author_image: https://avatars1.githubusercontent.com/u/5235856
author_image_width: 180
author_image_height: 180
author_image_mime: image/png

# Share settings
share_buttons: on

# Comments settings
disqus_shortname: www-diginfo-me

# Sidebar settings
sidebar: left # left|right
social_widget: on
subscribe_widget: on
copyright_notice: on

# Social settings
github_username:  FreezeSoul
weibo_username: FreezeSoul
twitter_username: FreezeSoul


# Mailchimp.com - Email subscribtion settings
# Refer to http://kb.mailchimp.com/lists/signup-forms/advanced-form-customization
# help in http://402v.com/ghostbo-ke-shi-yong-mailchimppei-zhi-you-jian-ding-yue/
form_action: "https://diginfo.us22.list-manage.com/subscribe/post?u=3cbaec778b9f7d17102c88bca&id=43af183afd"
list_id: "b_3cbaec778b9f7d17102c88bca_43af183afd"

# Formspree.io - Contact form settings
# Note: submit form once to activate
email: freezesoul@gmail.com
formspree_form_action: "https://formspree.io/f/mvzzkwgy"

# Sass settings
sass:
    style: :compressed

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
